In [2]:
import pandas as pd

In [ ]:
data = pd.read_csv('../data-csv/user.csv')

In [5]:
data

,id,gender,birthday,grade,region,last_visited
0,1,М,02.11.2007,9.0,Город Санкт-Петербург,23.08.2023 03:04:14
1,2,Ж,29.01.2009,8.0,Город Москва,07.09.2023 09:21:35
2,3,М,09.05.2007,NaN,Город Санкт-Петербург,23.08.2023 18:32:18
3,4,Ж,27.09.2007,9.0,Город Москва,18.08.2023 07:34:11
4,5,Ж,04.08.2007,NaN,Город Москва,02.09.2023 18:31:30
...,...,...,...,...,...,...
995,996,Ж,30.09.2008,8.0,Новосибирская область,22.08.2023 00:17:00
996,997,М,03.04.2007,10.0,Город Санкт-Петербург,19.08.2023 00:44:00
997,998,Ж,21.10.2007,9.0,Новосибирская область,07.09.2023 09:22:31
998,999,Ж,11.04.2008,9.0,Город Москва,05.09.2023 21:35:30
999,1000,Ж,20.03.2010,7.0,Город Москва,05.09.2023 04:20:50

In [ ]:
data['birthday'].dtype #пандас не приводит типы, поэтому надо менять самим либо указывать атрибут при создании parse_dates=['date_created'], date_format='%d.%m.%Y'

## Сколько в таблице user представлено учеников, родившихся в сентябре?

In [6]:
data['birthday'] = pd.to_datetime(data['birthday'], format='%d.%m.%Y')

In [7]:

month_count = data.groupby(data['birthday'].dt.month)['id'].count()

In [ ]:
month_count.loc[9] #9-сентябрь

np.int64(73)

## Какое количество учеников последний раз посещали платформу в первые 14 дней сентября?

In [9]:
data['last_visited'] = pd.to_datetime(data['last_visited'], format='%d.%m.%Y %H:%M:%S')

In [10]:
data['last_visited'].dtype

dtype('<M8[us]')

In [ ]:
data[(data['last_visited'].dt.month == 9) & (data['last_visited'].dt.day <= 14)].count() #dt как окуляр работает

id              377
gender          377
birthday        377
grade           308
region          377
last_visited    377
dtype: int64

## На сколько человек в данных больше девятиклассников, чем девятиклассниц?

In [6]:
data.groupby(['grade', 'gender'])['id'].count()

grade  gender
7.0    Ж         101
       М         104
8.0    Ж         112
       М         111
9.0    Ж          96
       М         101
10.0   Ж          99
       М         107
Name: id, dtype: int64

## Какой процент учеников, у которых указан класс, обучается в 9 классе?

### Ответ округлите до целых.

In [10]:
import numpy as np

In [8]:
data_without_nan = data.copy()

In [ ]:
data_without_nan = data_without_nan[data_without_nan['grade']!= np.nan] # 1 способ сделать датафрейм где в колонке grade нету пропусков НЕ РАБОТАЕТ

In [ ]:
data_without_nan = data_without_nan[data_without_nan['grade'].notna()] # 2 способ

In [17]:
data_without_nan

,id,gender,birthday,grade,region,last_visited
0,1,М,02.11.2007,9.0,Город Санкт-Петербург,23.08.2023 03:04:14
1,2,Ж,29.01.2009,8.0,Город Москва,07.09.2023 09:21:35
3,4,Ж,27.09.2007,9.0,Город Москва,18.08.2023 07:34:11
5,6,Ж,08.11.2009,7.0,Город Москва,03.09.2023 03:14:22
6,7,М,01.05.2007,10.0,Краснодарский край,22.08.2023 20:00:45
...,...,...,...,...,...,...
995,996,Ж,30.09.2008,8.0,Новосибирская область,22.08.2023 00:17:00
996,997,М,03.04.2007,10.0,Город Санкт-Петербург,19.08.2023 00:44:00
997,998,Ж,21.10.2007,9.0,Новосибирская область,07.09.2023 09:22:31
998,999,Ж,11.04.2008,9.0,Город Москва,05.09.2023 21:35:30
999,1000,Ж,20.03.2010,7.0,Город Москва,05.09.2023 04:20:50

In [24]:
data_without_nan.groupby('grade')['id'].count()

grade
7.0     205
8.0     223
9.0     197
10.0    206
Name: id, dtype: int64

In [22]:
data_without_nan['id'].count()

np.int64(831)

In [ ]:
procent_9 = round((197/831)*100, 0)
procent_9

24.0

In [ ]:
data_n = data.copy()

#### Идея такая: в датафрейме заменить nan на mean и тогда ответ не поменяет значение

In [ ]:
grade_n = round(data_n['grade'].dropna().mean(), 2) # проверка

In [41]:
grade_n

np.float64(8.49)

## Сколько в данных представлено учеников из регионов, в названиях которых в качестве подстроки содержится слово «город»?

### При расчёте статистики приведите названия регионов к строчному написанию.

In [18]:
data.loc[data['region'].str.lower().str.contains('город'),'region'].count()

np.int64(765)