In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('../practice-time/user.csv', )

In [4]:
data

,id,gender,birthday,grade,region,last_visited
0,1,М,02.11.2007,9.0,Город Санкт-Петербург,23.08.2023 03:04:14
1,2,Ж,29.01.2009,8.0,Город Москва,07.09.2023 09:21:35
2,3,М,09.05.2007,NaN,Город Санкт-Петербург,23.08.2023 18:32:18
3,4,Ж,27.09.2007,9.0,Город Москва,18.08.2023 07:34:11
4,5,Ж,04.08.2007,NaN,Город Москва,02.09.2023 18:31:30
...,...,...,...,...,...,...
995,996,Ж,30.09.2008,8.0,Новосибирская область,22.08.2023 00:17:00
996,997,М,03.04.2007,10.0,Город Санкт-Петербург,19.08.2023 00:44:00
997,998,Ж,21.10.2007,9.0,Новосибирская область,07.09.2023 09:22:31
998,999,Ж,11.04.2008,9.0,Город Москва,05.09.2023 21:35:30
999,1000,Ж,20.03.2010,7.0,Город Москва,05.09.2023 04:20:50

In [5]:
data['birthday'].dtype

### Сколько в таблице user представлено учеников, родившихся в сентябре?

In [6]:
data['birthday'] = pd.to_datetime(data['birthday'], format='%d.%m.%Y')

In [7]:

month_count = data.groupby(data['birthday'].dt.month)['id'].count()

In [8]:
month_count.loc[9]

np.int64(73)

### Какое количество учеников последний раз посещали платформу в первые 14 дней сентября?

In [9]:
data['last_visited'] = pd.to_datetime(data['last_visited'], format='%d.%m.%Y %H:%M:%S')

In [10]:
data['last_visited'].dtype

dtype('<M8[us]')

In [11]:
data

       id gender   birthday  grade                 region        last_visited
0       1      М 2007-11-02    9.0  Город Санкт-Петербург 2023-08-23 03:04:14
1       2      Ж 2009-01-29    8.0           Город Москва 2023-09-07 09:21:35
2       3      М 2007-05-09    NaN  Город Санкт-Петербург 2023-08-23 18:32:18
3       4      Ж 2007-09-27    9.0           Город Москва 2023-08-18 07:34:11
4       5      Ж 2007-08-04    NaN           Город Москва 2023-09-02 18:31:30
..    ...    ...        ...    ...                    ...                 ...
995   996      Ж 2008-09-30    8.0  Новосибирская область 2023-08-22 00:17:00
996   997      М 2007-04-03   10.0  Город Санкт-Петербург 2023-08-19 00:44:00
997   998      Ж 2007-10-21    9.0  Новосибирская область 2023-09-07 09:22:31
998   999      Ж 2008-04-11    9.0           Город Москва 2023-09-05 21:35:30
999  1000      Ж 2010-03-20    7.0           Город Москва 2023-09-05 04:20:50

[1000 rows x 6 columns]

In [12]:
data[(data['last_visited'].dt.month == 9) & (data['last_visited'].dt.day <= 14)].count()

id              377
gender          377
birthday        377
grade           308
region          377
last_visited    377
dtype: int64

На сколько человек в данных больше девятиклассников, чем девятиклассниц?

In [13]:
data.groupby(['grade', 'gender'])['id'].count()

grade  gender
7.0    Ж         101
       М         104
8.0    Ж         112
       М         111
9.0    Ж          96
       М         101
10.0   Ж          99
       М         107
Name: id, dtype: int64

In [14]:
data_without_nan = data.copy()

In [15]:
import numpy as np

In [81]:
data_without_nan = data_without_nan[data_without_nan['grade']!= np.nan]

In [16]:
data_without_nan = data_without_nan[data_without_nan['grade'].notna()]

In [ ]:
data_without_nan

np.float64(8.486161251504212)

In [24]:
data_without_nan.groupby('grade')['id'].count()

grade
7.0     205
8.0     223
9.0     197
10.0    206
Name: id, dtype: int64

In [22]:
data_without_nan['id'].count()

np.int64(831)

In [28]:
procent_9 = round((197/831)*100,0)
procent_9

24.0

In [29]:
data_n = data.copy()

In [30]:
data_n

       id gender   birthday  grade                 region        last_visited
0       1      М 2007-11-02    9.0  Город Санкт-Петербург 2023-08-23 03:04:14
1       2      Ж 2009-01-29    8.0           Город Москва 2023-09-07 09:21:35
2       3      М 2007-05-09    NaN  Город Санкт-Петербург 2023-08-23 18:32:18
3       4      Ж 2007-09-27    9.0           Город Москва 2023-08-18 07:34:11
4       5      Ж 2007-08-04    NaN           Город Москва 2023-09-02 18:31:30
..    ...    ...        ...    ...                    ...                 ...
995   996      Ж 2008-09-30    8.0  Новосибирская область 2023-08-22 00:17:00
996   997      М 2007-04-03   10.0  Город Санкт-Петербург 2023-08-19 00:44:00
997   998      Ж 2007-10-21    9.0  Новосибирская область 2023-09-07 09:22:31
998   999      Ж 2008-04-11    9.0           Город Москва 2023-09-05 21:35:30
999  1000      Ж 2010-03-20    7.0           Город Москва 2023-09-05 04:20:50

[1000 rows x 6 columns]

In [40]:
grade_n = round(data_n['grade'].dropna().mean(), 2)

In [41]:
grade_n

np.float64(8.49)

In [34]:
data_n

       id gender   birthday  grade                 region        last_visited
0       1      М 2007-11-02    9.0  Город Санкт-Петербург 2023-08-23 03:04:14
1       2      Ж 2009-01-29    8.0           Город Москва 2023-09-07 09:21:35
2       3      М 2007-05-09    NaN  Город Санкт-Петербург 2023-08-23 18:32:18
3       4      Ж 2007-09-27    9.0           Город Москва 2023-08-18 07:34:11
4       5      Ж 2007-08-04    NaN           Город Москва 2023-09-02 18:31:30
..    ...    ...        ...    ...                    ...                 ...
995   996      Ж 2008-09-30    8.0  Новосибирская область 2023-08-22 00:17:00
996   997      М 2007-04-03   10.0  Город Санкт-Петербург 2023-08-19 00:44:00
997   998      Ж 2007-10-21    9.0  Новосибирская область 2023-09-07 09:22:31
998   999      Ж 2008-04-11    9.0           Город Москва 2023-09-05 21:35:30
999  1000      Ж 2010-03-20    7.0           Город Москва 2023-09-05 04:20:50

[1000 rows x 6 columns]